# Generated by Django 4.2.3 on 2023-07-13 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Heroe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('nombre_real', models.CharField(max_length=256)),
                ('residencia', models.CharField(max_length=256)),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('peso', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Poder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Villano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('nombre_real', models.CharField(max_length=256)),
                ('residencia', models.CharField(max_length=256)),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('peso', models.IntegerField(null=True)),
            ],
        ),
    ]
